#ifndef SERVER_CONSTANTS
#define SERVER_CONSTANTS


#define INITIAL_PROMPT "Welcome to My Bank!\nYou are?\n1. Admin\t2. Customer\nPress any other number to exit\nEnter the choice number"

// ------------------ COMMON TEXT ---------------------------

// LOGIN
#define LOGIN_ID "Enter your login ID"
#define PASSWORD "Enter your password \n# "
#define INVALID_LOGIN "Entered login ID doesn't exist!$"
#define INVALID_PASSWORD "Entered password doesn't match!$"
#define SALT_BAE "666"

// GET ACCOUNT DETAILS
#define GET_ACCOUNT_NUMBER "Enter the account number of the account you are looking for"
#define GET_CUSTOMER_ID "Enter the customer ID of the customer you are looking for"

#define ERRON_INPUT_FOR_NUMBER "You have entered a sequence of alphabets when a number was expected or you have entered an invalid number!\nYou will now be redirected to the main menu^"

#define INVALID_MENU_CHOICE "Invalid menu choice\nYou will now be redirected to the main menu!^"

#define CUSTOMER_ID_DOESNT_EXIT "No customer exists of the given ID"
#define CUSTOMER_LOGIN_ID_DOESNT_EXIT "No customer exists of the given login ID$"

#define ACCOUNT_ID_DOESNT_EXIT "No account exists of the given account number"

#define TRANSACTIONS_NOT_FOUND "No transactions were performed on this account by the customer!^"

// ------------------------------------------------------------------------

// ---------------------------- ADMIN SPECIFIC TEXT---------------------------

// LOGIN WELCOME
#define ADMIN_LOGIN_WELCOME "Welcome dear Admin!\nEnter your credentials to Login"
#define ADMIN_LOGIN_SUCCESS "Hello, you have successfully logged in"

// ADMIN MENU
#define ADMIN_MENU "1. Get Customer Details\n2. Get Account Details\n3. Get Transaction details\n4. Add Account\n5. Delete Account\n6. Modify Customer Information\nPress any other key to logout"

// ADD CUSTOMER
#define ADMIN_ADD_CUSTOMER_PRIMARY "Enter the details for the primary customer\n"
#define ADMIN_ADD_CUSTOMER_SECONDARY "Enter the details for the secondary customer\n"
#define ADMIN_ADD_CUSTOMER_NAME "Enter customer's name?"
#define ADMIN_ADD_CUSTOMER_GENDER "Enter customer's gender?\nEnter M for male, F for female and O for others"
#define ADMIN_ADD_CUSTOMER_AGE "Enter customer's age?"
#define ADMIN_ADD_CUSTOMER_AUTOGEN_LOGIN "The autogenerated login ID for the customer is : "
#define AUTOGEN_PASSWORD "software" // append to end of next string macro
#define ADMIN_ADD_CUSTOMER_AUTOGEN_PASSWORD "The autogenerated password for the customer is : "
#define ADMIN_ADD_CUSTOMER_WRONG_GENDER "You entered a wrong gender choice!\nYou'll now be redirected to the main menu!^"

// ADD ACCOUNT
#define ADMIN_ADD_ACCOUNT_TYPE "Type of account is to be created? Enter 1 for regular account and 2 for joint account"
#define ADMIN_ADD_ACCOUNT_NUMBER "The newly created account's number is :"

// DELETE ACCOUNT
#define ADMIN_DEL_ACCOUNT_NO "Enter the account number of the account you want to delete?"
#define ADMIN_DEL_ACCOUNT_SUCCESS "Entered account has been successfully deleted\nRedirecting you to the main menu ....^"
#define ADMIN_DEL_ACCOUNT_FAILURE "Entered account cannot be deleted since it still has some money\nRedirecting you to the main menu ....^"

// MODIFY CUSTOMER INFO
#define ADMIN_MOD_CUSTOMER_ID "Enter the ID of the customer who's information you want to edit"
#define ADMIN_MOD_CUSTOMER_MENU "Information you want to modify?\n1. Name 2. Age 3. Gender \nPress any other key to cancel"
#define ADMIN_MOD_CUSTOMER_NEW_NAME "Enter the updated value for name?"
#define ADMIN_MOD_CUSTOMER_NEW_GENDER "Enter the updated value for gender?"
#define ADMIN_MOD_CUSTOMER_NEW_AGE "Enter the updated value for age?"

#define ADMIN_MOD_CUSTOMER_SUCCESS "The required modification was successfully made!\nYou'll now be redirected to the main menu...^"

#define ADMIN_LOGOUT "Logging you out now! Good bye!$"

// ====================================================

// ========== CUSTOMER SPECIFIC TEXT===================

// LOGIN WELCOME
#define CUSTOMER_LOGIN_WELCOME "Welcome dear customer! Enter your credentials to access to your account!"
#define CUSTOMER_LOGIN_SUCCESS "Welcome beloved customer!"

#define CUSTOMER_LOGOUT "Logging you out now dear customer! Good bye!$"

// ADMIN MENU
#define CUSTOMER_MENU "1. Get Customer Details\n2. Deposit Money\n3. Withdraw Money\n4. Get Balance\n5. Get Transaction information\n6. Change Password\nPress any other key to logout"

#define ACCOUNT_DEACTIVATED "Your account has been deactivated!^"

#define DEPOSIT_AMOUNT "Amount you want to add into your bank?"
#define DEPOSIT_AMOUNT_INVALID "You entered an invalid amount!^"
#define DEPOSIT_AMOUNT_SUCCESS "The specified amount has been successfully added to your bank account!^"

#define WITHDRAW_AMOUNT "Amount you want to withdraw from your bank?"
#define WITHDRAW_AMOUNT_INVALID "You seem to have either passed an invalid amount or you don't have enough money in your bank to withdraw the specified amount^"
#define WITHDRAW_AMOUNT_SUCCESS "The specified amount has been successfully withdrawn from your bank account!^"

#define PASSWORD_CHANGE_OLD_PASS "Enter your old password"
#define PASSWORD_CHANGE_OLD_PASS_INVALID "The entered password doesn't match with the old password"
#define PASSWORD_CHANGE_NEW_PASS "Enter the new password"
#define PASSWORD_CHANGE_NEW_PASS_RE "Reenter the new password"
#define PASSWORD_CHANGE_NEW_PASS_INVALID "The new password and the reentered passwords don't seem to pass!^"
#define PASSWORD_CHANGE_SUCCESS "Password successfully changed!^"

// ====================================================


#define ACCOUNT_FILE "./records/account.bank"
#define CUSTOMER_FILE "./records/customer.bank"
#define TRANSACTION_FILE "./records/transactions.bank"

#endif